### ISSUE TITLE
What is a component model?

### ISSUE THREAD

**Issue by sivabudh** [pranav-srinivas-kumar/python-zcm#1]
Sorry, this probably will come across as quite dumb and pointless, but...

What's a component model? What's the rationale behind this project? What sort of use cases can I apply this project to? Why does it need to use ZMQ?

Just a few questions. I'm an avid ZMQ follower and saw @hintjens retweeting this repo.

Hope it's ok to ask a question like this. Thanks!

**Comment by p-ranav** [comment]
Hey! Your questions are neither dumb nor pointless. To understand Component Models, you need to understand Component-based Software Engineering (CBSE) and what it stands for.

## What is CBSE?

Component-based Software Engineering is concerned with the rapid assembly and maintenance of component-based systems, where:
- components and platforms have certified properties 
- these certified properties provide the basis for predicting properties of systems built from components.

## LEGOS and Component Models

Think of LEGO toys. Large, complex LEGO toys (software applications) are built by "composing" (connecting) small tested building blocks - LEGO pieces (software components). Each LEGO piece has a clear shape (definition) and this shape defines what the piece can connect with (interfaces). CBSE is a reuse-based approach to defining, implementing, and composing loosely-coupled software components into systems. 

In the industry, time to market for software is quite important - incorporate successful innovations quickly. This also means that modern software engineering promotes "rapid system prototyping" i.e. easy removal and addition of functionality. This is where component models are useful.

The size & complexity of modern software is increasingly rapidly. Think about a flight controller software on a Boeing... or even just Matlab. Single products quickly become part of a product family. Software is upgraded after deployment. Applications are built from components that were never intended to work together. 

A component model aims to be a sort of specification. One that clearly describes how to define software components, implement this components, and connect the components together. An individual software component is a software package, a web service, a web resource, or a module that encapsulates a set of related functions (or data).

## Example: Simple Flight Controller

Let's talk with examples. Think of a flight controller application. This application is basically part of a control system; one that needs to (1) get sensor data from devices on the aircraft e.g. GPS, inertial measurement units and save the current state of the aircraft e.g. latitude, longitude, surface altitude, pitch, roll, yaw etc. Using this sensor data, the flight controller must decide what to do next and control the craft. Control is done by actuating control surfaces on the wings of the plane. 

If you were to write the complete software for this application, how would you do it? 

There are two ways I can think of: 
- The BAD way:
  - Write a program that does everything in one place. 
  - Who cares about software reuse?
  - The program (1) maintains a high-level state machine, (2) fetches sensor data, (3) decides what to do next, and (4) controls the craft based on some PID control

Why is the above method bad? Well it doesn't separate concerns - The entire application is just built into one blob of complex code that cannot be distributed i.e. executed on multiple communicating devices over a network. The entire program _has_ to run on a single computer. 
- The CBSE way
  - Design the applications as a set of composed, interacting components
  - Example: sensor_component, pid_component, actuator_component, high_level_control_component
  - The component model specifies how these components are defined, implemented, executed etc. 
  - Each component becomes an small building block e.g. a unique thread, and interacts with each other using some middleware platform e.g. ZeroMQ
  - A sensor component is loosely coupled with the high-level control component i.e. they are separate threads that have a clear interaction pattern
  - What is the pattern? 
    - The sensor component is periodically triggered by a timer
    - The sensor component handles this time-trigger - prepares a message and publishes this message to the high-level controller, over the network
    - The high-level controller receives this message on a subscriber port, and now knows the current state of the aircraft
  - How did this help? 
    - Now the sensor and high-level controller are separate components with clearly defined interfaces and loose coupling
    - If the sensor component fails, you can restart it without having to worry about other components
    - Since the sensor component is separated from the other components, it can be executed on a different device in the network - This reduces the load on the CPU and literally separates the concerns.

## So, what's the component model in python-zcm?
- In ZCM, this is the component:
  ![rosmod_component](https://cloud.githubusercontent.com/assets/8450091/15991267/50ae2a6e-3073-11e6-8d79-606d2a5bcf5d.png)
- The above component looks a lot like a LEGO block - a concrete core with edges sticking out that indicate how this component can be connected with other components.
- Components are building blocks (of code) that have ports and timers and some core logic. 
- Components support four basic types of ports - Publishers, Subscribers, Clients, and Servers - All these ports use ZeroMQ in the back-end. 
- So the sensor component we looked at before will be a software component that:
  - Has a periodic timer that triggers the component e.g. with a  period of 50 ms
  - Has an operation that is executed every time the timer expires
  - Inside this time-triggered operation, the sensor prepares a message for the high-level controller and publishes this message
- Each component has an operation queue - this queue receives messages and requests from other components
  - The high-level controller receives on message on its subscriber port from the sensor component
  - This message manifests in the high-level controller's operation queue
- Each component has an executor thread that handles messages in the operation queue
  - So the executor thread in the high-level controller looks at the first message in the queue and executes an handler operation that handles this message
- A component model like this adds concrete execution semantics to an application; semantics that can be used to study the system as a whole. You can analyze the application you've built and reason about its properties by studying the individual components

## Where's ZeroMQ in all this?
- All communication between components is done via ZeroMQ
- Publisher, Subscriber, Client and Server ports in a component wrap around ZeroMQ sockets and provide structure to communication
- You can also use Google's protobuf to serialize complex data structures into strings before sending this data down the wire using ZeroMQ

## One Final Example Use-Case

User Requirements: Design a complete system for your phone/tablet that can control the lights in the room
- How would you design a set of components to do this?
- You have two or maybe three embedded devices e.g. BeagleBone Black or Raspberry Pi at your disposal

Simple Design:
- You have a client user-facing app on your phone that gives you the touchscreen interface to switch the lights ON/OFF
- This GUI app interacts with a zcm component in the back-end and messages this component about the user's choice. 
- This high-level component now needs to do something about it
- Let's say the room has a smart control box attached to the wall, like a thermostat, and is part of the same WiFi network as your phone
- Let's say this control box is running Debian Linux and there is a zcm component that is ready and waiting to take requests to control the lights
- You can use your phone, and your local network to effectively communicate with this control box
  - Separation of concerns has been achieved - The user's choice is separated from the control box which may be doing so many other things. 
  - if you didn't separate concerns, you'd have designed this like a traditional embedded device i.e. a physical switch on the control box that needs to be pressed. This defeats the purpose of the application.
  - Component to Component interaction has been achieved thanks to ZeroMQ and networking
  - Very little needs to change if you want the user to also be able to control the lights

Hope I've answered your questions. Do let me know if you need additional resources.

**Comment by sivabudh** [comment]
@pranav-srinivas-kumar Thank you so much for such a detailed answer. 👍 I hope this project becomes a success. I will give it a try when I have the chance!
